/*
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package come.settings.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import come.settings.client.model.HierarchicalModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * HierarchicalModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-26T12:39:48.178-05:00")
public class HierarchicalModel {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("leftWeight")
  private Integer leftWeight = null;

  @JsonProperty("rightWeight")
  private Integer rightWeight = null;

  @JsonProperty("children")
  private List<HierarchicalModel> children = null;

  @JsonProperty("name")
  private String name = null;

  public HierarchicalModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public HierarchicalModel leftWeight(Integer leftWeight) {
    this.leftWeight = leftWeight;
    return this;
  }

   /**
   * Get leftWeight
   * @return leftWeight
  **/
  @ApiModelProperty(value = "")
  public Integer getLeftWeight() {
    return leftWeight;
  }

  public void setLeftWeight(Integer leftWeight) {
    this.leftWeight = leftWeight;
  }

  public HierarchicalModel rightWeight(Integer rightWeight) {
    this.rightWeight = rightWeight;
    return this;
  }

   /**
   * Get rightWeight
   * @return rightWeight
  **/
  @ApiModelProperty(value = "")
  public Integer getRightWeight() {
    return rightWeight;
  }

  public void setRightWeight(Integer rightWeight) {
    this.rightWeight = rightWeight;
  }

  public HierarchicalModel children(List<HierarchicalModel> children) {
    this.children = children;
    return this;
  }

  public HierarchicalModel addChildrenItem(HierarchicalModel childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<HierarchicalModel>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @ApiModelProperty(value = "")
  public List<HierarchicalModel> getChildren() {
    return children;
  }

  public void setChildren(List<HierarchicalModel> children) {
    this.children = children;
  }

  public HierarchicalModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HierarchicalModel hierarchicalModel = (HierarchicalModel) o;
    return Objects.equals(this.id, hierarchicalModel.id) &&
        Objects.equals(this.leftWeight, hierarchicalModel.leftWeight) &&
        Objects.equals(this.rightWeight, hierarchicalModel.rightWeight) &&
        Objects.equals(this.children, hierarchicalModel.children) &&
        Objects.equals(this.name, hierarchicalModel.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, leftWeight, rightWeight, children, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HierarchicalModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    leftWeight: ").append(toIndentedString(leftWeight)).append("\n");
    sb.append("    rightWeight: ").append(toIndentedString(rightWeight)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

