/*
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package come.settings.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import come.settings.client.model.SettingWriteModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SettingsWriteModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-26T12:39:48.178-05:00")
public class SettingsWriteModel {
  @JsonProperty("settingsToUpdate")
  private List<SettingWriteModel> settingsToUpdate = null;

  public SettingsWriteModel settingsToUpdate(List<SettingWriteModel> settingsToUpdate) {
    this.settingsToUpdate = settingsToUpdate;
    return this;
  }

  public SettingsWriteModel addSettingsToUpdateItem(SettingWriteModel settingsToUpdateItem) {
    if (this.settingsToUpdate == null) {
      this.settingsToUpdate = new ArrayList<SettingWriteModel>();
    }
    this.settingsToUpdate.add(settingsToUpdateItem);
    return this;
  }

   /**
   * Get settingsToUpdate
   * @return settingsToUpdate
  **/
  @ApiModelProperty(value = "")
  public List<SettingWriteModel> getSettingsToUpdate() {
    return settingsToUpdate;
  }

  public void setSettingsToUpdate(List<SettingWriteModel> settingsToUpdate) {
    this.settingsToUpdate = settingsToUpdate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettingsWriteModel settingsWriteModel = (SettingsWriteModel) o;
    return Objects.equals(this.settingsToUpdate, settingsWriteModel.settingsToUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(settingsToUpdate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettingsWriteModel {\n");
    
    sb.append("    settingsToUpdate: ").append(toIndentedString(settingsToUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

