#!/usr/bin/env bash 

script_dir=$(dirname "$0") && cd $script_dir && script_dir=$(pwd) && source ./_helpers
requireDependency 'dotnet' '1.0.4'
requireDependency 'npm'

_log 'Building projects - Backend'
cd ../src/Settings
dotnet build

_log 'Building projects - Frontend'
cd "$script_dir"
cd ../src/Settings.Web
npm run build
