#!/usr/bin/env bash

script_dir=$(dirname "$0") && cd $script_dir && script_dir=$(pwd) && source ./_helpers
requireDependency 'docker'
requireDependency 'docker-compose'

_log 'Building projects'
cd ../
docker-compose build backend

# if in appveyor, don't do frontend things
if [ -z "$APPVEYOR" ] ; then
    _log 'Building projects - Frontend'
    docker-compose build frontend
fi
