#!/usr/bin/env bash 

script_dir=$(dirname "$0") && cd $script_dir && source ./_helpers

function executeStep {
    local step=$1 
    
    _log "Executing Step: $step"
    $step || {
        _log "FAILED: $1";
        exit 1
    }
}
