#!/usr/bin/env bash

script_dir=$(dirname "$0") && cd $script_dir && script_dir=$(pwd) && source ./_helpers

_log 'Removing spurious intermediate images'
docker rmi $(docker images -f dangling=true -q)
