#!/usr/bin/env bash 

script_dir=$(dirname "$0") && cd $script_dir && script_dir=$(pwd) && source ./_helpers
requireDependency 'dotnet'
requireDependency 'npm'

_log 'Spinning up server - backend and frontend'

{
    cd $script_dir && \
    cd ../src/Settings && \
    dotnet run; 
} &

{ 
    cd $script_dir && \
    cd ../src/Settings.Web && \
    npm run start:local;
} & 

wait -n
kill 0