#!/usr/bin/env bash 

script_dir=$(dirname "$0") && cd $script_dir && script_dir=$(pwd) && source ./_helpers
# requireDependency 'dotnet' '1.0.4'
requireDependency 'npm'

# TODO: clarify intent for serving/hosting app - locally it appears to work fine from frotnend only
# cd $script_dir
# cd ../src/Settings
# dotnet run

_log 'Spinning up server'
cd $script_dir
cd ../src/Settings.Web
npm run start