#!/usr/bin/env bash

script_dir=$(dirname "$0") && cd $script_dir && script_dir=$(pwd) && source ./_helpers

_log 'Spinning up server - backend and frontend'

if [ "$1" == "native" ] ; then
  requireDependency 'dotnet'
  requireDependency 'npm'

  {
      cd $script_dir && \
      cd ../src/Settings && \
      dotnet run;
  } &

  {
      cd $script_dir && \
      cd ../src/Settings.Web && \
      npm run start:local;
  } &

  wait -n
  kill 0
else
  requireDependency 'docker'
  requireDependency 'docker-compose'

  docker-compose up
fi
