/*
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.settings.client.api;

import come.settings.client.model.HierarchicalModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApplicationsApi
 */
@Ignore
public class ApplicationsApiTest {

    private final ApplicationsApi api = new ApplicationsApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiApplicationsAddParentparentAppIdNewnamePostTest() {
        String name = null;
        Integer parentAppId = null;
        HierarchicalModel response = api.apiApplicationsAddParentparentAppIdNewnamePost(name, parentAppId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiApplicationsByApplicationNameGetTest() {
        String applicationName = null;
        HierarchicalModel response = api.apiApplicationsByApplicationNameGet(applicationName);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiApplicationsGetTest() {
        HierarchicalModel response = api.apiApplicationsGet();

        // TODO: test validations
    }
    
}
