/*
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.settings.client.api;

import come.settings.client.model.HierarchicalModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnvironmentsApi
 */
@Ignore
public class EnvironmentsApiTest {

    private final EnvironmentsApi api = new EnvironmentsApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiEnvironmentsAddParentparentEnvIdNewnamePostTest() {
        String name = null;
        Integer parentEnvId = null;
        HierarchicalModel response = api.apiEnvironmentsAddParentparentEnvIdNewnamePost(name, parentEnvId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiEnvironmentsByEnvironmentNameGetTest() {
        String environmentName = null;
        HierarchicalModel response = api.apiEnvironmentsByEnvironmentNameGet(environmentName);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiEnvironmentsGetTest() {
        HierarchicalModel response = api.apiEnvironmentsGet();

        // TODO: test validations
    }
    
}
