/*
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.settings.client.api;

import come.settings.client.model.SettingReadModel;
import come.settings.client.model.SettingsWriteModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SettingsApi
 */
@Ignore
public class SettingsApiTest {

    private final SettingsApi api = new SettingsApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiSettingsByApplicationNameByEnvironmentNameGetTest() {
        String applicationName = null;
        String environmentName = null;
        List<SettingReadModel> response = api.apiSettingsByApplicationNameByEnvironmentNameGet(applicationName, environmentName);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiSettingsCreateUpdateByApplicationNameByEnvironmentNamePostTest() {
        String applicationName = null;
        String environmentName = null;
        SettingsWriteModel settings = null;
        Boolean response = api.apiSettingsCreateUpdateByApplicationNameByEnvironmentNamePost(applicationName, environmentName, settings);

        // TODO: test validations
    }
    
}
